modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPL 3.0"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="nihonium" #mandatory
version="${file.jarVersion}" #mandatory
displayName="nihonium" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="nihonium.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Arrokoth233" #optional

description='''
This mod will "IMPROVE" your fps.
'''

[[dependencies.nihonium]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[47,)" #mandatory
   ordering="NONE"
   side="BOTH"

[[dependencies.nihonium]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.21)"
   ordering="NONE"
   side="BOTH"
